const layout_enUS_linux = [
  [
    { code: 'Escape', key: 'Escape', label: 'Esc' },
    { code: 'F1', key: 'F1' },
    { code: 'F2', key: 'F2' },
    { code: 'F3', key: 'F3' },
    { code: 'F4', key: 'F4' },
    { code: 'F5', key: 'F5' },
    { code: 'F6', key: 'F6' },
    { code: 'F7', key: 'F7' },
    { code: 'F8', key: 'F8' },
    { code: 'F9', key: 'F9' },
    { code: 'F10', key: 'F10' },
    { code: 'F11', key: 'F11' },
    { code: 'F12', key: 'F12' },
    { code: 'Home', key: 'Home' },
    { code: 'End', key: 'End' },
    { code: 'Insert', key: 'Insert' },
    { code: 'Delete', key: 'Delete' }
  ],
  [
    { code: 'Backquote', key: '` ~', label: "~<br>`" },
    { code: 'Digit1', key: '1 !', label: "!<br>1" },
    { code: 'Digit2', key: '2 @', label: "@<br>2" },
    { code: 'Digit3', key: '3 #', label: "#<br>3" },
    { code: 'Digit4', key: '4 $', label: "$<br>4" },
    { code: 'Digit5', key: '5 %', label: "%<br>5" },
    { code: 'Digit6', key: '6 ^', label: "^<br>6" },
    { code: 'Digit7', key: '7 &', label: "&<br>7" },
    { code: 'Digit8', key: '8 *', label: "*<br>8" },
    { code: 'Digit9', key: '9 (', label: "(<br>9" },
    { code: 'Digit0', key: '0 )', label: ")<br>0" },
    { code: 'Minus', key: '- =', label: "_<br>-" },
    { code: 'Equal', key: '= +', label: "+<br>=" },
    { code: 'Backspace', key: 'Backspace' }
  ],
  [
    { code: 'Tab', key: 'Tab' },
    { code: 'KeyQ', key: 'Q' },
    { code: 'KeyW', key: 'W' },
    { code: 'KeyE', key: 'E' },
    { code: 'KeyR', key: 'R' },
    { code: 'KeyT', key: 'T' },
    { code: 'KeyY', key: 'Y' },
    { code: 'KeyU', key: 'U' },
    { code: 'KeyI', key: 'I' },
    { code: 'KeyO', key: 'O' },
    { code: 'KeyP', key: 'P' },
    { code: 'BracketLeft', key: '[ {', label: "{<br>[" },
    { code: 'BracketRight', key: '] }', label: "{<br>]" },
    { code: 'Backslash', key: '\\ |', label: "|<br>\\" }
  ],
  [
    { code: 'CapsLock', key: 'CapsLock' },
    { code: 'KeyA', key: 'A' },
    { code: 'KeyS', key: 'S' },
    { code: 'KeyD', key: 'D' },
    { code: 'KeyF', key: 'F' },
    { code: 'KeyG', key: 'G' },
    { code: 'KeyH', key: 'H' },
    { code: 'KeyJ', key: 'J' },
    { code: 'KeyK', key: 'K' },
    { code: 'KeyL', key: 'L' },
    { code: 'Semicolon', key: '; :', label: ":<br>;" },
    { code: 'Quote', key: `' "`, label: "\"<br>'" },
    { code: 'Enter', key: 'Enter' }
  ],
  [
    { code: 'ShiftLeft', key: 'Shift' },
    { code: 'KeyZ', key: 'Z' },
    { code: 'KeyX', key: 'X' },
    { code: 'KeyC', key: 'C' },
    { code: 'KeyV', key: 'V' },
    { code: 'KeyB', key: 'B' },
    { code: 'KeyN', key: 'N' },
    { code: 'KeyM', key: 'M' },
    { code: 'Comma', key: ', <', label: "<<br>," },
    { code: 'Period', key: '. >', label: "><br>." },
    { code: 'Slash', key: '/ ?', label: "?<br>/" },
    { code: 'ShiftRight', key: 'Shift' }
  ],
  [
    { code: 'WakeUp', key: 'WakeUp', label: 'Fn' },
    { code: 'ControlLeft', key: 'Control', label: 'Ctrl' },
    { code: 'AltLeft', key: 'Alt' },
    { code: 'Space', key: ' ' },
    { code: 'AltRight', key: 'AltGraph', label: 'Alt' },
    { code: 'ControlRight', key: 'Control', label: 'Ctrl' },
    { code: 'PageUp', key: 'PageUp', label: 'PgUp' },
    { code: 'ArrowUp', key: 'ArrowUp', label: '⬆' },
    { code: 'PageDown', key: 'PageDown', label: 'PgDn' }
  ],
  [{ code: 'ArrowLeft', key: 'ArrowLeft', label: '⬅' },
  { code: 'ArrowDown', key: 'ArrowDown', label: '⬇' },
  { code: 'ArrowRight', key: 'ArrowRight', label: '➡' }]
];

export default layout_enUS_linux