import CharacterSet, { Character } from "../core/CharacterSet";
import { KeyCapLabelMap } from "../core/Keyboard";

export const mockCharacters: Character[] = [
  { code: ["KeyA"], glyph: "a", type: 'LOWERCASE_LETTER', behavior: 'APPEND' },
  { code: ["KeyB"], glyph: "b", type: 'LOWERCASE_LETTER', behavior: 'APPEND' },
  { code: ["KeyC"], glyph: "c", type: 'LOWERCASE_LETTER', behavior: 'APPEND' },
  { code: ["KeyD"], glyph: "d", type: 'LOWERCASE_LETTER', behavior: 'APPEND' },

  // DIGITS
  { code: ["Digit0"], glyph: "0", type: 'NUMBER', behavior: 'APPEND' },
  { code: ["Digit1"], glyph: "1", type: 'NUMBER', behavior: 'APPEND' },
  { code: ["Digit2"], glyph: "2", type: 'NUMBER', behavior: 'APPEND' },
  { code: ["Digit3"], glyph: "3", type: 'NUMBER', behavior: 'APPEND' },
  { code: ["Digit4"], glyph: "4", type: 'NUMBER', behavior: 'APPEND' },
  { code: ["Digit5"], glyph: "5", type: 'NUMBER', behavior: 'APPEND' },
  { code: ["Digit6"], glyph: "6", type: 'NUMBER', behavior: 'APPEND' },
  { code: ["Digit7"], glyph: "7", type: 'NUMBER', behavior: 'APPEND' },
  { code: ["Digit8"], glyph: "8", type: 'NUMBER', behavior: 'APPEND' },
  { code: ["Digit9"], glyph: "9", type: 'NUMBER', behavior: 'APPEND' },

  // PUNCTUATION
  { code: ["Comma"], glyph: ",", type: 'PUNCTUATION', behavior: 'APPEND' },
  { code: ["Quote"], glyph: "'", type: 'PUNCTUATION', behavior: 'SPLIT' },
  { code: ["Quote"], glyph: '"', type: 'PUNCTUATION', behavior: 'BRACKET' },

  // SYMBOLS
  { code: ["Digit2"], glyph: "@", type: 'SPECIAL', behavior: 'SPLIT' },
  { code: ["Digit3"], glyph: "#", type: 'SPECIAL', behavior: 'PREPEND' },
  { code: ["Digit4"], glyph: "$", type: 'SPECIAL', behavior: 'APPEND' },
  { code: ["Digit6"], glyph: "^", type: 'SPECIAL', behavior: 'OPERATOR' },
  { code: ["Backquote"], glyph: "`", type: 'SPECIAL', behavior: 'BRACKET' },
  { code: ["BracketLeft", "BracketRight"], glyph: "[", bracketPair: "]", type: 'SPECIAL', behavior: 'BRACKET' },

]

export const mockCharacterSet = new CharacterSet(mockCharacters)

export const mockKeyCapLabelMap:KeyCapLabelMap = {
  NONE: { main: "" },
  Backquote: { main: "`", shift: "~" },
  Digit1: { main: "1", shift: "!" },
  Digit2: { main: "2", shift: "@" },
  Digit3: { main: "3", shift: "#" },
  Digit4: { main: "4", shift: "$" },
  Digit5: { main: "5", shift: "%" },
  Digit6: { main: "6", shift: "^" },
  Digit7: { main: "7", shift: "&" },
  Digit8: { main: "8", shift: "*" },
  Digit9: { main: "9", shift: "(" },
  Digit0: { main: "0", shift: ")" },
  Minus: { main: "-", shift: "_" },
  Equal: { main: "=", shift: "+" },
  Backspace: { main: "Backspace" },
  Tab: { main: "Tab" },
  KeyQ: { main: "q", shift: "Q" },
  KeyW: { main: "w", shift: "W" },
  KeyE: { main: "e", shift: "E" },
  KeyR: { main: "r", shift: "R" },
  KeyT: { main: "t", shift: "T" },
  KeyY: { main: "y", shift: "Y" },
  KeyU: { main: "u", shift: "U" },
  KeyI: { main: "i", shift: "I" },
  KeyO: { main: "o", shift: "O" },
  KeyP: { main: "p", shift: "P" },
  BracketLeft: { main: "[", shift: "{" },
  BracketRight: { main: "]", shift: "}" },
  Backslash: { main: "\\", shift: "|" },
  CapsLock: { main: "CapsLock" },
  KeyA: { main: "a", shift: "A" },
  KeyS: { main: "s", shift: "S" },
  KeyD: { main: "d", shift: "D" },
  KeyF: { main: "f", shift: "F" },
  KeyG: { main: "g", shift: "G" },
  KeyH: { main: "h", shift: "H" },
  KeyJ: { main: "j", shift: "J" },
  KeyK: { main: "k", shift: "K" },
  KeyL: { main: "l", shift: "L" },
  Semicolon: { main: ";", shift: ":" },
  Quote: { main: "'", shift: '"' },
  Enter: { main: "Enter" },
  ShiftLeft: { main: "Shift" },
  KeyZ: { main: "z", shift: "Z" },
  KeyX: { main: "x", shift: "X" },
  KeyC: { main: "c", shift: "C" },
  KeyV: { main: "v", shift: "V" },
  KeyB: { main: "b", shift: "B" },
  KeyN: { main: "n", shift: "N" },
  KeyM: { main: "m", shift: "M" },
  Comma: { main: ",", shift: "<" },
  Period: { main: ".", shift: ">" },
  Slash: { main: "/", shift: "?" },
  ShiftRight: { main: "Shift" },
  ControlLeft: { main: "Ctrl" },
  AltLeft: { main: "Alt" },
  Space: { main: "" },
  AltRight: { main: "Alt" },
  ControlRight: { main: "Ctrl" }
}