import { Finger, Hand, KeyboardFingerMap, KeyboardPhysicalLayout } from "./layouts"

export const StandardPhysicalLayout: KeyboardPhysicalLayout = {
  0: ['Escape','F1','F2','F3','F4','F5','F6','F7','F8','F9','F10','F11','F12','Home','End','Insert','Delete'],
  1: ['Backquote','Digit1','Digit2','Digit3','Digit4','Digit5','Digit6','Digit7','Digit8','Digit9','Digit0','Minus','Equal','Backspace'],
  2: ['Tab','KeyQ','KeyW','KeyE','KeyR','KeyT','KeyY','KeyU','KeyI','KeyO','KeyP','BracketLeft','BracketRight','Backslash'],
  3: ['CapsLock','KeyA','KeyS','KeyD','KeyF','KeyG','KeyH','KeyJ','KeyK','KeyL','Semicolon','Quote','Enter'],
  4: ['ShiftLeft','KeyZ','KeyX','KeyC','KeyV','KeyB','KeyN','KeyM','Comma','Period','Slash','ShiftRight'],
  5: ['WakeUp','ControlLeft','AltLeft','Space','AltRight','ControlRight','PageUp','ArrowUp','PageDown'],
  6: ['ArrowLeft', 'ArrowDown', 'ArrowRight']
}
export const StandardFingerMap: KeyboardFingerMap = {
  NONE: { hand: Hand.ANY, finger: Finger.ANY },
  Escape: { hand: Hand.LEFT, finger: Finger.RING },
  F1: { hand: Hand.LEFT, finger: Finger.RING },
  F2: { hand: Hand.LEFT, finger: Finger.RING },
  F3: { hand: Hand.LEFT, finger: Finger.MIDDLE },
  F4: { hand: Hand.LEFT, finger: Finger.MIDDLE },
  F5: { hand: Hand.LEFT, finger: Finger.MIDDLE },
  F6: { hand: Hand.LEFT, finger: Finger.INDEX },
  F7: { hand: Hand.LEFT, finger: Finger.INDEX },
  F8: { hand: Hand.RIGHT, finger: Finger.INDEX },
  F9: { hand: Hand.RIGHT, finger: Finger.MIDDLE },
  F10: { hand: Hand.RIGHT, finger: Finger.MIDDLE },
  F11: { hand: Hand.RIGHT, finger: Finger.MIDDLE },
  F12: { hand: Hand.RIGHT, finger: Finger.RING },
  Home: { hand: Hand.RIGHT, finger: Finger.RING },
  End: { hand: Hand.RIGHT, finger: Finger.RING },
  Insert: { hand: Hand.RIGHT, finger: Finger.RING },
  Delete: { hand: Hand.RIGHT, finger: Finger.RING },
  Backquote: { hand: Hand.LEFT, finger: Finger.RING },
  Digit1: { hand: Hand.LEFT, finger: Finger.RING },
  Digit2: { hand: Hand.LEFT, finger: Finger.RING },
  Digit3: { hand: Hand.LEFT, finger: Finger.MIDDLE },
  Digit4: { hand: Hand.LEFT, finger: Finger.MIDDLE },
  Digit5: { hand: Hand.LEFT, finger: Finger.INDEX },
  Digit6: { hand: Hand.LEFT, finger: Finger.INDEX },
  Digit7: { hand: Hand.RIGHT, finger: Finger.INDEX },
  Digit8: { hand: Hand.RIGHT, finger: Finger.MIDDLE },
  Digit9: { hand: Hand.RIGHT, finger: Finger.MIDDLE },
  Digit0: { hand: Hand.RIGHT, finger: Finger.RING },
  Minus: { hand: Hand.RIGHT, finger: Finger.RING },
  Equal: { hand: Hand.RIGHT, finger: Finger.RING },
  Backspace: { hand: Hand.RIGHT, finger: Finger.RING },
  Tab: { hand: Hand.LEFT, finger: Finger.PINKY },
  KeyQ: { hand: Hand.LEFT, finger: Finger.PINKY },
  KeyW: { hand: Hand.LEFT, finger: Finger.RING },
  KeyE: { hand: Hand.LEFT, finger: Finger.MIDDLE },
  KeyR: { hand: Hand.LEFT, finger: Finger.MIDDLE },
  KeyT: { hand: Hand.LEFT, finger: Finger.INDEX },
  KeyY: { hand: Hand.RIGHT, finger: Finger.INDEX },
  KeyU: { hand: Hand.RIGHT, finger: Finger.INDEX },
  KeyI: { hand: Hand.RIGHT, finger: Finger.MIDDLE },
  KeyO: { hand: Hand.RIGHT, finger: Finger.RING },
  KeyP: { hand: Hand.RIGHT, finger: Finger.RING },
  BracketLeft: { hand: Hand.RIGHT, finger: Finger.PINKY },
  BracketRight: { hand: Hand.RIGHT, finger: Finger.PINKY },
  Backslash: { hand: Hand.RIGHT, finger: Finger.PINKY },
  CapsLock: { hand: Hand.LEFT, finger: Finger.PINKY },
  KeyA: { hand: Hand.LEFT, finger: Finger.PINKY },
  KeyS: { hand: Hand.LEFT, finger: Finger.RING },
  KeyD: { hand: Hand.LEFT, finger: Finger.MIDDLE },
  KeyF: { hand: Hand.LEFT, finger: Finger.INDEX },
  KeyG: { hand: Hand.LEFT, finger: Finger.INDEX },
  KeyH: { hand: Hand.RIGHT, finger: Finger.INDEX },
  KeyJ: { hand: Hand.RIGHT, finger: Finger.INDEX },
  KeyK: { hand: Hand.RIGHT, finger: Finger.MIDDLE },
  KeyL: { hand: Hand.RIGHT, finger: Finger.RING },
  Semicolon: { hand: Hand.RIGHT, finger: Finger.PINKY },
  Quote: { hand: Hand.RIGHT, finger: Finger.PINKY },
  Enter: { hand: Hand.RIGHT, finger: Finger.PINKY },
  ShiftLeft: { hand: Hand.LEFT, finger: Finger.PINKY },
  KeyZ: { hand: Hand.LEFT, finger: Finger.RING },
  KeyX: { hand: Hand.LEFT, finger: Finger.MIDDLE },
  KeyC: { hand: Hand.LEFT, finger: Finger.INDEX },
  KeyV: { hand: Hand.LEFT, finger: Finger.INDEX },
  KeyB: { hand: Hand.ANY, finger: Finger.INDEX },
  KeyN: { hand: Hand.RIGHT, finger: Finger.INDEX },
  KeyM: { hand: Hand.RIGHT, finger: Finger.INDEX },
  Comma: { hand: Hand.RIGHT, finger: Finger.MIDDLE },
  Period: { hand: Hand.RIGHT, finger: Finger.RING },
  Slash: { hand: Hand.RIGHT, finger: Finger.PINKY },
  ShiftRight: { hand: Hand.RIGHT, finger: Finger.PINKY },
  WakeUp: { hand: Hand.LEFT, finger: Finger.PINKY },
  ControlLeft: { hand: Hand.LEFT, finger: Finger.PINKY },
  AltLeft: { hand: Hand.LEFT, finger: Finger.MIDDLE },
  Space: { hand: Hand.ANY, finger: Finger.THUMB },
  AltRight: { hand: Hand.RIGHT, finger: Finger.INDEX },
  ControlRight: { hand: Hand.RIGHT, finger: Finger.RING },
  PageUp: { hand: Hand.RIGHT, finger: Finger.INDEX },
  ArrowUp: { hand: Hand.RIGHT, finger: Finger.MIDDLE },
  PageDown: { hand: Hand.RIGHT, finger: Finger.RING },
  ArrowLeft: { hand: Hand.RIGHT, finger: Finger.INDEX },
  ArrowDown: { hand: Hand.RIGHT, finger: Finger.MIDDLE },
  ArrowRight: { hand: Hand.RIGHT, finger: Finger.RING },
}
